### ISSUE TITLE
Simplified tslint.json causes “Cannot convert undefined or null to object” error

### ISSUE THREAD

**Issue by LukeSw** [schuchard/prettier-schematic#10]
**Describe the bug**
When airbnb rules are used, and tslint.json is simplified to:
`{
  "extends": "tslint-config-airbnb",
  "rulesDirectory": ["node_modules/codelyzer"]
}`

then `ng g @schuchard/prettier:add` commands shows “Cannot convert undefined or null to object” error after answering all questions.

**To Reproduce**
1. Replace tslint.json with the content mentioned above.
2. Run `npm install @schuchard/prettier@latest --save-dev`
3. Run `npx ng g @schuchard/prettier:add` and answer all questions.
4. See “Cannot convert undefined or null to object” error.

**Expected behavior**
No error, tslint.json updated if necessary.

**Desktop (please complete the following information):**
 - OS: Windows
 - Node Version: v10.13.0
 - Angular & Angular/CLI Version: 7.1.3

**Comment by schuchard** [comment]
Thanks for reporting.

**Comment by schuchard** [comment]
Thanks again for narrowing in on the issue. The 2.1.0 release should resolve this issue. When testing I noticed that the `tslint-config-airbnb` rules had some conflicts with the default Prettier rules so you may have to adjust the Prettier rules to work with that rule set. Fortunately line length and quote style are configurable


Example:
```
ERROR: /Users/schuchard/dev/repos/prettier-schematic/sandbox/src/app/app.component.spec.ts[16, 6]: ` should be "
ERROR: /Users/schuchard/dev/repos/prettier-schematic/sandbox/src/polyfills.ts[59, 1]: Exceeds maximum line length of 100
ERROR: /Users/schuchard/dev/repos/prettier-schematic/sandbox/src/polyfills.ts[61, 1]: Exceeds maximum line length of 100
```
