### ISSUE TITLE
[Question] How have you found using it with Angular?

### ISSUE THREAD

**Issue by BBlackwo** [schuchard/prettier-schematic#14]
Not sure if this is the right forum, but I'd like to hear people's experience using Prettier in an Angular project. I'm hesitant to use it because of this issue: [How can I prevent prettier from taking multi-line array to a single line? #352](https://github.com/prettier/prettier-vscode/issues/352).

**Comment by schuchard** [comment]
I've used Prettier and this schematic on most of my projects without any issues. I think the issue you referenced boils down to the broader issue of Prettier in general. You either like how Prettier formats or you don't. So far, I haven't seen any Angular specific issues using Prettier. If you have please share. For me, the consistency and readability Prettier offers as a whole far out ways issues like the one linked above :)
