### ISSUE TITLE
update to a recent version of the CLI's DevKit

### ISSUE THREAD

**Issue by Splaktar** [schuchard/prettier-schematic#49]
**Describe the bug**
https://github.com/angular/components/issues/21045

**To Reproduce**
1. run `ng update @angular/core @angular/cli @angular/material` in a project on Angular v10 to update to v11

**Expected behavior**
No exceptions.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: macOS
 - Node Version: 14.15.0
 - Angular & Angular/CLI Version: 11.0.0 and CLI 11.0.1

**Additional context**
The deprecated Workspace APIs were removed in v11. It looks like these schematics need some updates to the newest CLI DevKit.

**Comment by schuchard** [comment]
Thanks for reporting @Splaktar. I've update the dependencies and the test sandbox to Angular 11. Let me know if there's still an issue.

The latest package is now published at v `4.0.0`
