### ISSUE TITLE
use strict: command not found when @schuchard/prettier installed after prettier.

### ISSUE THREAD

**Issue by pierceray** [schuchard/prettier-schematic#57]
**Describe the bug**
The bug manifests when `@schuchard/prettier` is installed after prettier.  In my scenario, I was doing it through `npm ci` on a build machine, but you can run `npm i prettier && npm i @schuchard/prettier` to replicate it. 

The output is:
```
$ npx prettier --write "**/*.{js,json,css,md,ts,html,component.html}"
/source/test/node_modules/.bin/prettier: line 1: use strict: command not found
/source/test/node_modules/.bin/prettier: line 2: syntax error near unexpected token `exports,'
/source/test/node_modules/.bin/prettier: line 2: `Object.defineProperty(exports, "__esModule", { value: true });'
```

**To Reproduce**
1. `npm i prettier && npm i @schuchard/prettier`
2. `npx prettier --write "**/*.{js,json,css,md,ts,html,component.html}"`
3. See error

**Expected behavior**
Prettier runs as expected

**Desktop (please complete the following information):**
 - OS: MacOS
 - Node Version 12
 - Angular & Angular/CLI Version

**Additional context**
From my investigation, it appears that this library is overwriting the symlink for prettier in `node_modules/.bin/prettier`.  

By doing an `ls -ahl node_modules/.bin/prettier` you can see where the symlinks point.

After `prettier` is installed: `prettier -> ../prettier/bin-prettier.js` after 
After `@schuchard/prettier` is installed: `prettier -> ../@schuchard/prettier/src/prettier/index.js`

Now I'm not sure what the actual bug is.  Whether it is that the prettier symlink is being overwritten, or that the script file that it is linking to doesn't have the proper `#!/usr/bin/env node` as the [npm bin docs](https://docs.npmjs.com/cli/v6/configuring-npm/package-json#bin) says to do.

My intuition is that the prettier library bin symlink shouldn't be overwritten.

**Comment by schuchard** [comment]
Hi @pierceray, please refer to the readme for install instructions. This library is intended to be installed as a schematic with `ng add @schuchard/prettier`

**Comment by schuchard** [comment]
Closing for now, let me know if you're still seeing an issue after running the schematic with `ng add`. Thanks.

**Comment by abraham** [comment]
Same issue. I deleted existing `.prettierignore` and `prettier.config.js`, ran `npx ng add @schuchard/prettier` and still get the error.

You can check it out at https://github.com/abraham/slides-today/pull/1771

**Comment by Splaktar** [comment]
I see this when updating from 4.0.0 to 5.0.0 of this library in the package.json. Should I be using `ng update` instead?

**Comment by Splaktar** [comment]
Hrm, that didn't work
```
ERROR! .prettierignore already exists.
ERROR! prettier.config.js already exists.
The Schematic workflow failed. See above.
```

**Comment by Splaktar** [comment]
I tried to reinstall prettier and got this error:
```
npm i prettier --save-dev
npm WARN rm not removing /Users/splaktar/Git/pink-summit/onscene-rms-nextgen/node_modules/.bin/prettier as it wasn't installed by /Users/splaktar/Git/pink-summit/onscene-rms-nextgen/node_modules/prettier
```
Doing `rm node_modules/.bin/prettier` and then `npm i prettier --save-dev` again fixed it. I agree with the OP that this schematic should not be overwriting the prettier symlink.
