### ISSUE TITLE
Remove `git add` to comply with lint-staged recommendations

### ISSUE THREAD

**Issue by Den-dp** [schuchard/prettier-schematic#60]
**Is your feature request related to a problem? Please describe.**
`lint-staged` since v10 doesn't recommend to use `git add` accordingly to https://github.com/okonet/lint-staged/releases/tag/v10.0.0 (BREAKING CHANGES) because now they do it internally.

**Describe the solution you'd like**
So if I understand correctly the `lint-staged` configuration can be simplified via removing `git add`.

**Comment by schuchard** [comment]
Thanks for reporting. Fixed in #61 and released in `5.0.0`
