### ISSUE TITLE
index.js Windows Script Host Syntax Error 800A03EA

### ISSUE THREAD

**Issue by CMiksche** [schuchard/prettier-schematic#64]
**Describe the bug**
After upgrading my Ionic Angular project from 9 to 11 and replacing tslint with eslint I get a Windows Script Host error.

**To Reproduce**
Upgrade an existing Angular project from version 9 to 11 and replace tslint with eslint

**Expected behavior**
I don't expect that windows outputs an error. 

**Screenshots**
![windows_script_host](https://user-images.githubusercontent.com/9869391/103161038-a44fc300-47dc-11eb-8a92-5bf46bb7ba00.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Node Version 12.16.2
 - Angular & Angular/CLI Version 11.0.5

**Additional context**
It seems like the real error is that the index.js file doesn't get executed by node?

**Comment by CMiksche** [comment]
Seems like my issue was that I forgot to uninstall `tslint-config-prettier` ...

**Comment by CMiksche** [comment]
> Seems like my issue was that I forgot to uninstall `tslint-config-prettier` ...

Okay, there seems to be no connection to that. I uninstalled `tslint-config-prettier` and still have the error.

Interestingly I updated four Angular projects and only had this issue with two of them.

**Comment by bogacg** [comment]
I'm getting same error too 😥

**Comment by ashishkrtewari** [comment]
@bogacg @CMiksche 

I also faced the same issue after following the mentioned steps on the repo main page.
To fix the issue -
1. Remove the @schuchar/prettier, from package.json
2. run `npm install`
3. Replace the prettier package with the official one, using
`npm install --save-dev --save-exact prettier`
as mentioned [here](https://prettier.io/docs/en/install.html)
4. `npm run prettier`
