### ISSUE TITLE
Error running command in root directory

### ISSUE THREAD

**Issue by dpetla** [schuchard/prettier-schematic#7]
**Describe the bug**
Received the error bellow after attempting to add through the command `ng g @schuchard/prettier:add`

***Error:***
` Expected end of file, got ",
{
  "extends": [
 ..." at 108:1. `

**To Reproduce**
1. Install globally `npm install -g @schuchard/prettier`
2. Run in an Angular CLI root directory `ng g @schuchard/prettier:add`
3. Select options as shown in the screenshot below

**Expected behavior**
Process to complete without errors and the creation of prettier and tslint config files.

**Screenshots**
![screen shot 2018-10-30 at 10 16 44 pm](https://user-images.githubusercontent.com/16305783/47762106-9d2ada00-dc91-11e8-9975-793861264d8a.jpg)

**Desktop**
Angular CLI: 7.0.2
Node: 9.11.1
OS: darwin x64
Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.10.2
@angular-devkit/core         7.0.2
@angular-devkit/schematics   7.0.2
@schematics/angular          7.0.2
@schematics/update           0.10.2
rxjs                         6.3.3
typescript                   3.1.3

**Comment by dpetla** [comment]
Hi @schuchard, it is a public [project](https://github.com/dpetla/Menote) but the problem was solved when I deleted a pre-existent `./tslint.json` file. Thanks for your help and nice work on this project.

**Comment by schuchard** [comment]
Glad you were able to figure it out :)
