### ISSUE TITLE
Prettier fails in CI

### ISSUE THREAD

**Issue by fvanwijk** [schuchard/prettier-schematic#79]
**Describe the bug**

In have installed the schematic and added `script: npm run prettier` script to my Azure Pipeline.
It runs `prettier -c \"**/*.{js,json,css,scss,less,md,ts,html,component.html}\"` as configuring in package.json scripts.

This will call node_modules/.bin/prettier which is a symlink to index.js of this package.

The error in the pipeline I get is:
> /home/vsts/work/1/s/src/node_modules/.bin/prettier: 1: use strict: not found
> /home/vsts/work/1/s/src/node_modules/.bin/prettier: 2: Syntax error: word unexpected (expecting ")")

It seems that it is trying to execute the Node script as bash.

I can reproduce it by running `npm ci` locally and then `npm run prettier`.
When I add this to index.js:1 manually, everything works:
```
#!/usr/bin/env node
```

Can you reproduce this? If this is really a bug, the above solution might work for everyone.

**Comment by fvanwijk** [comment]
Never mind.
index.js is the install script, not the prettier script. So above fix removes the error but when executed as if it is prettier this is a noop.

After running `npm i prettier -D` again, the .bin/prettier symlink is overwritten and everything works as expected.

So there must be something wrong with this package taking over the prettier bin symlink.

**Comment by Den-dp** [comment]
Right, this line overwrites the prettier symlink 
https://github.com/schuchard/prettier-schematic/blob/b26246475493865ddf11ca4df189e5f2850c5fb3/package.json#L27
and should be removed (or rewritten as an object with a different key https://docs.npmjs.com/cli/v7/configuring-npm/package-json#bin )

Related to #64

**Comment by schuchard** [comment]
this should be addressed in #81 with version 5.1.0. Let me know if you still have an issue.
