### ISSUE TITLE
Error running command in powershell

### ISSUE THREAD

**Issue by osnoser1** [schuchard/prettier-schematic#8]
**Describe the bug**

![image](https://user-images.githubusercontent.com/1179744/48215168-0aa4cd80-e358-11e8-9555-ead2643ff90d.png)

Changing single quotes for doubles in the script works

![image](https://user-images.githubusercontent.com/1179744/48215454-aa625b80-e358-11e8-9144-163542400fc6.png)

![image](https://user-images.githubusercontent.com/1179744/48215374-8141cb00-e358-11e8-9cbb-59819fd069fe.png)

**To Reproduce**
1. `npm run prettier`

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Node Version: 8.12.0
 - Angular & Angular/CLI Version: 7.0.3 & 7.0.4

PD: Thanks for amazing tool ❤

**Comment by schuchard** [comment]
Thank you for reporting _and_ debugging :) If you can test out then latest version (2.0.1) for the fix that would be very helpful. I don't have a Windows machine to verify with. Thanks!
