### ISSUE TITLE
Prettier --write failing in Local machine 

### ISSUE THREAD

**Issue by inconsolableanki** [schuchard/prettier-schematic#80]
<img width="1044" alt="Screenshot 2021-07-20 at 8 14 30 PM" src="https://user-images.githubusercontent.com/29491504/126344760-747cd121-c574-46b4-8334-3d0c0b5e064c.png">
My package Json file 
{
  "name": "salesforce-app",
  "private": true,
  "version": "1.0.0",
  "description": "Salesforce App",
  "scripts": {
    "lint": "npm run lint:aura && npm run lint:lwc",
    "lint:aura": "eslint --fix **/aura/**/*",
    "lint:lwc": "eslint --fix **/lwc/**/*",
    "test": "npm run test:unit",
    "test:unit": "sfdx-lwc-jest",
    "test:unit:watch": "sfdx-lwc-jest --watch",
    "test:unit:debug": "sfdx-lwc-jest --debug",
    "test:unit:coverage": "sfdx-lwc-jest --coverage",
    "prettier": "prettier --write \"force-app/main/default/{aura,classes,lwc}/**/*.{css,js,cmp,xml,cls,html}\"",
    "prettier:verify": "prettier --list-different \"force-app/main/default/{aura,classes,lwc}/**/*.{css,js,cmp,xml,cls,html}\"",
    "prepare": "husky install"
  },
  "devDependencies": {
    "@lwc/eslint-plugin-lwc": "^1.0.1",
    "@prettier/plugin-xml": "^0.13.1",
    "@salesforce/eslint-config-lwc": "^2.0.0",
    "@salesforce/eslint-plugin-aura": "^2.0.0",
    "@salesforce/eslint-plugin-lightning": "^0.1.1",
    "@salesforce/sfdx-lwc-jest": "^0.12.6",
    "eslint": "^7.29.0",
    "eslint-config-airbnb-base": "^14.2.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-import": "^2.23.4",
    "eslint-plugin-jest": "^24.3.6",
    "eslint-plugin-prettier": "^3.4.0",
    "husky": "^7.0.0",
    "lint-staged": "^11.0.0",
    "prettier": "^2.3.2",
    "prettier-plugin-apex": "^1.10.0"
  },
  "lint-staged": {
    "force-app/main/default/{aura,classes,lwc}/**/*.{css,js,cmp,xml,cls,html}": [
      "prettier --write"
    ],
    "force-app/main/default/{aura,lwc}/**/*": [
      "eslint --fix"
    ]
  }
}

When I stage my changes and run commit --amend, prettier --write is running, while running it getting failed

Node version 14 and npm 6 version i have

**Comment by schuchard** [comment]
it looks like you've narrowed the files that the prettier command can run against `force-app/main/default/{aura,classes,lwc}/**/*.{css,js,cmp,xml,cls,html}`

is that a requirement for your app?

**Comment by LogicLuminaryy** [comment]
Yes that’s correct

But my issue has resolved by pointing java11

**Comment by schuchard** [comment]
Great, I'll close this issue then. Thanks.
